const express = require("express");
const userController = require("../controllers/userController");
const projectController = require("../controllers/projectController");
const generateController = require("../controllers/generateController");
const designController = require("../controllers/designController");
const validateGenerate = require("../middleware/validateGenerate");
const authMiddleware = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/generate", authMiddleware , validateGenerate , generateController.validation);
router.post("/analyze" , authMiddleware , generateController.selectedDesign);
router.post("/projects" , authMiddleware , projectController.createProject);
router.post("/users" , userController.createUser);
router.post("/login" , userController.loginUser);
router.get("/projects" , authMiddleware , projectController.getProjects);
router.get("/projects/:id", authMiddleware , projectController.getProjectById);
router.get("/designs" , designController.getDesigns);
router.get("/designs/:id" , designController.getDesignsById);
router.delete("/designs/:id" , authMiddleware , designController.deleteDesign);
router.delete("/projects/:id" , authMiddleware ,projectController.deleteProject);
router.put("/designs/:id" , designController.updateDesign);
router.put("/reset-password" , userController.resetPassword);
module.exports = router;
console.log("generateRoutes.js was completed");